### PR TITLE
(PUP-12050) Check for nested Sensitive arguments

### LINKED ISSUE #9384: file resource type displays Sensitive information in clear text in output when Deferred
## Describe the Bug
We are passing a Sensitive object from vault_lookup to the file resource type using stdlib::deferrable_epp.
Running `puppet agent --test` results in the updated secret being rendered to the screen in plain text.

## Expected Behavior
The file resource type should not render Sensitive variable values in clear text in file difference output. The value rendered to output should be changed from Redacted to Redacted.

## Steps to Reproduce
```
$my_vars = {
  'url' => $external_url,
  'app_id' => $external_app_id,
  'app_token => Deferred('vault_lookup::lookup', [
      $path_to_app_id_token, {
          'vault_addr' => $vault_url,
          'cert_role'  => $servertype,
          'field'      => 'app_id_token_pw',
      },
  ]),
}

file { '/opt/my_app/my_script.sh':
  ensure  => file,
  owner   => 'root',
  group   => 'root',
  mode    => '0750',
  content => stdlib::deferrable_epp("${module_name}/opt/my_app/my_script.sh.epp", $my_vars),
}
```

1. In HashiCorp vault, update the token value.
2. On the Linux server, execute: `sudo puppet agent --test`
3. The output should show the new token value and the old token value in clear text.

## Environment
 - Version puppet-agent 8.5.1, puppetlabs-stdlib 9.6.0, and puppet-vault_lookup 1.1.0
 - Platform Ubuntu 22.04

## Additional Context
I'm pretty sure the secret was not displayed when it changed under puppet 7.24.

### PR DESCRIPTION
**Pull request by joshcooper**
Previously, a manifest containing nested Deferred values did not mark the corresponding parameter as sensitive, resulting in the following:

    $ cat manifest.pp
    $vars = {'token' => Deferred('new', [Sensitive, "password"])}
    file { '/tmp/a.sh':
      ensure  => file,
      content => Deferred('inline_epp', ['<%= $token %>', $vars])
    }
    $ truncate --size 0 /tmp/a.sh
    $ puppet apply --show_diff manifest.pp
    Notice: Compiled catalog for localhost in environment production in 0.01 seconds
    Notice: /Stage[main]/Main/File[/tmp/a.sh]/content:
    --- /tmp/a.sh	2024-07-03 17:30:37.024543314 -0700
    +++ /tmp/puppet-file20240703-1784698-2cu5s9	2024-07-03 17:30:41.880572413 -0700
    @@ -0,0 +1 @@
    +password
    \ No newline at end of file

The issue occurred because we were only checking if the outermost DeferredValue contained any Sensitive arguments, in this case the arguments passed to `inline_epp` function, but not the `password` passed to the `new` function.

This is not an issue when deferred values are preprocessed, because Deferred values are completely resolved and we can check if resolved value is Sensitive.

The problem was introduced in b92e4d35cc1bc38777b5df0c81d543cd46b73565 which added the ability to lazily call a deferred function when its respective resource is evaluated. It should be backported to 7.x

With this change we get:

    $ puppet apply --show_diff manifest.pp
    Notice: Compiled catalog for localhost in environment production in 0.01 seconds
    Notice: /Stage[main]/Main/File[/tmp/a.sh]/content: [diff redacted]
    Notice: /Stage[main]/Main/File[/tmp/a.sh]/content: changed [redacted] to [redacted]
    Notice: Applied catalog in 0.04 seconds

Fixes #9384

### CODE REVIEW

File: lib/puppet/pops/evaluator/deferred_resolver.rb [hunk 1]
```diff
@@ -109,6 +117,22 @@ def resolve_futures(catalog)
     end
   end
 
+  # Return true if x contains an argument of type PSensitiveType. It
+  # short-circuits as soon as a value is found.
+  #
+  def contains_sensitive_args(x)
```
Comment (joshcooper) [inline lib/puppet/pops/evaluator/deferred_resolver.rb:123]:
```suggestion
  def contains_sensitive_args?(x)
```

**Comment by joshcooper** [comment]
Rubocop failures should be fixed in https://github.com/puppetlabs/puppet/pull/9413

**Review by cthorn42 — APPROVED** [review]
